"""Render the markdown mirror — same drill order, same vocabulary, no
interaction (wf-projections#D001): deterministic anchors, <details> folds,
controls degrade to instructions."""


def render_md(bundle, vocab):
    doc = bundle["canonical"]
    asks_block, model_view, post = bundle["asks"], bundle["model_view"], bundle["posture"]
    run = doc.get("code_state") or {}
    lines = [
        "<!-- generated by archwright-report — do not edit; regenerate from the canonical JSON bundle -->",
        "# %s — Design Check" % bundle["project"],
        "",
        "checked %s · %s%s" % (bundle["generated_at"], (run.get("commit") or "no-git")[:7],
                               " (dirty)" if run.get("dirty") else ""),
        "",
    ]
    if post == "all-clear":
        lines.append("%s %s" % (vocab.status_glyph("pass"), vocab.surface("all-clear")))
    elif post in ("tool-error", "empty-project"):
        lines.append(vocab.surface(post))
    else:
        c = asks_block["counts"]
        lines.append("%d decisions · %d approvals waiting" % (c["decision"], c["approval"] - c["auto_approved"]))
    lines.append("")

    if model_view["states"]:
        lines += ["## How %s works" % bundle["project"], "", "```mermaid", "stateDiagram-v2"]
        for el in model_view["states"]:
            lines.append('    %s: %s' % (el["id"].replace("-", "_"), el["label"]))
        lines += ["```", ""]

    blocking = [a for a in asks_block["asks"] if not a["auto_approved"]]
    if blocking:
        lines += ["## Needs attention", ""]
        for a in blocking:
            anchor = a["ask_id"].replace(":", "-")
            lines.append('### %s [%s] <a id="ask-%s"></a>' % (a["title"], a["confidence_phrase"], anchor))
            cp = a.get("contrast_pair")
            if cp:
                lines += ["", "The design says: %s" % cp.get("expected"),
                          "The code does: %s" % cp.get("actual")]
            if a["ask_type"] == "decision":
                lines.append("")
                for opt in a.get("options") or []:
                    lines.append("- [ ] %s%s" % (opt["label"], " **(recommended)**" if opt["recommended"] else ""))
            else:
                lines += ["", "Recommended: **%s**" % a["recommendation"]["action"]]
            lines += ["", "> to respond, edit responses.json or reply in conversation", ""]

    pendings = [s for s in doc.get("skips") or [] if "pending" in (s.get("reason") or "")]
    skips = [s for s in doc.get("skips") or [] if "pending" not in (s.get("reason") or "")]
    baselined = [v for v in doc.get("violations") or [] if v.get("baselined")]
    lines += ["## What isn't verified", ""]
    if not (pendings or skips or baselined):
        lines.append("Nothing — every rule was checked this run.")
    for s in skips:
        lines.append("- %s %s — %s" % (vocab.status_glyph("skip"), vocab.surface("skip"), s.get("reason")))
    if pendings:
        lines.append("- %s %d rules: %s" % (vocab.status_glyph("pending"), len(pendings), vocab.surface("pending")))
    for v in baselined:
        lines.append("- %s %s — %s" % (vocab.status_glyph("warn"), vocab.surface("baselined"), v.get("message")))
    lines.append("")
    return "\n".join(lines)
