#!/usr/bin/env python3
"""archwright-import-woz: Convert a wizard_of_oz session export (woz-session/v1
JSON) into an archwright discovery artifact (ticket 025, grill Q05/Q01).

The JSON is wizard_of_oz's versioned external contract — this tool is the
CONSUMER side: mechanical conversion only (ledger entries, category mapping,
SUPERSEDES rendering). Interpretation — force evidence, model seed, screen
flow, draft behavior seeds — is skill work (archwright-woz-import), never
this tool's.

Usage:
    archwright-import-woz.py <export.json> [-o <design-dir>] [--force]

Output: <design-dir>/discovery/woz/woz-<session-id>.md (default design-dir:
./design). A kind: discovery artifact, status: proposed — conservation
warnings are expected until the skill's interpretation pass consumes the
entries; approval flips them to errors (ticket 026 gating).

Behavior:
- Unknown format version or unknown category = exit 1, errors on stderr,
  no output written (never a silent partial import).
- Existing output = exit 2 unless --force (imports are snapshots refreshed
  DELIBERATELY — grill Q1).
- Deterministic output (no timestamps) for golden-corpus comparison.
- Session prose (sim log, open questions) is rendered inside fenced blocks:
  it is verbatim evidence, and fencing keeps its D-number mentions out of the
  conservation citation graph (a transcript mention is not consumption).

Category mapping (consumer-side, grill Q2/Q05): identity for the 9 categories
shared with the archwright ledger enum; woz `aesthetic` → core `experience`
(experience generalizes it). Origins are identical enums — no mapping.

Exit codes: 0 = imported, 1 = input validation failure, 2 = usage/refusal.
"""

import argparse
import json
import re
import sys
from pathlib import Path

SUPPORTED_FORMAT = "woz-session/v1"
WOZ_CATEGORIES = {"mechanic", "feedback", "progression", "scope", "content",
                  "economy", "aesthetic", "narrative", "meta", "technical"}
CATEGORY_MAP = {"aesthetic": "experience"}  # everything else maps to itself
WOZ_ORIGINS = {"user", "suggested", "inferred"}


def fail(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def validate(export):
    errors = []
    if export.get("format") != SUPPORTED_FORMAT:
        errors.append(f"unsupported format '{export.get('format')}' — this consumer "
                      f"speaks {SUPPORTED_FORMAT} only")
        return errors  # nothing else is trustworthy under an unknown format
    session = export.get("session") or {}
    if not session.get("id"):
        errors.append("session.id missing")
    for bucket in ("decisions", "superseded"):
        for d in export.get(bucket) or []:
            num = d.get("number")
            cat = d.get("category", "")
            if cat not in WOZ_CATEGORIES:
                errors.append(f"decision {num}: unknown category '{cat}' — not in the "
                              f"woz-session/v1 enum (contract drift? regenerate the export)")
            if d.get("origin", "") not in WOZ_ORIGINS:
                errors.append(f"decision {num}: unknown origin '{d.get('origin')}'")
    return errors


def _entry_md(d, superseded_by=None):
    lines = [f"### D{d['number']:03d} — {d['title']}"]
    lines.append(f"- **Category:** {CATEGORY_MAP.get(d['category'], d['category'])}")
    lines.append(f"- **Origin:** {d['origin']}")
    decision = d["decision"]
    if d.get("supersedes") is not None:
        marker = f"SUPERSEDES D{d['supersedes']:03d}"
        # Trust boundary: wizard_of_oz's canonical exports (salvage-run) embed
        # the marker in the decision text; minimal exports don't. Prepend only
        # when absent so both render identically.
        if not decision.startswith(marker):
            decision = f"{marker}. {decision}"
    lines.append(f"- **Decision:** {decision}")
    lines.append(f"- **Rationale:** {d['rationale']}")
    lines.append(f"- **Alternatives:** {d['alternatives']}")
    if superseded_by is not None:
        lines.append(f"- **Superseded by:** D{superseded_by:03d}")
    return "\n".join(lines)


def _fenced(text):
    return f"```text\n{text}\n```"


def render(export):
    session = export["session"]
    session_id = session["id"]
    artifact_id = "woz-" + re.sub(r"[^a-z0-9-]+", "-", session_id.lower()).strip("-")

    out = [f"""---
kind: discovery
id: {artifact_id}
status: proposed
area: woz
serves: []
from_woz:
  format: {SUPPORTED_FORMAT}
  source: {export.get('source', '')}
  session: {session_id}
---

# WoZ Session Import: {session.get('title', session_id)}

<!-- Generated by archwright-import-woz.py — a snapshot with citation (grill Q1),
     refreshed deliberately via --force. Ledger entries are truth; the fenced
     prose below is verbatim session evidence. Interpretation (force evidence,
     model seed, screen flow) is the archwright-woz-import skill's work. -->

## Session

| Field | Value |
|-------|-------|
| Session | {session_id} |
| Status | {session.get('status', '')} (phase: {session.get('phase', '')}) |
| Elevator pitch | {session.get('elevator_pitch', '')} |
| Core loop | {session.get('core_loop', '')} |
| Aesthetics | {', '.join(session.get('aesthetics') or [])} |
| MLP features | {'; '.join(session.get('mlp_features') or [])} |
| Target audience | {session.get('target_audience', '')} |
| GDD companion | {export.get('gdd_companion', False)} |
""".rstrip()]

    # Ledger: ALL entries in number order — active and superseded interleaved
    # as originally appended. SUPERSEDES prefixes let the ticket-026 validator
    # exclude superseded targets from conservation, same as a native ledger.
    superseded_by = {d["number"]: d.get("superseded_by")
                     for d in export.get("superseded") or []}
    entries = list(export.get("decisions") or []) + list(export.get("superseded") or [])
    entries.sort(key=lambda d: d["number"])
    out.append("## Decisions")
    for d in entries:
        out.append(_entry_md(d, superseded_by=superseded_by.get(d["number"])))

    sim = export.get("simulation_log") or []
    if sim:
        out.append("## Simulation Log")
        for seg in sim:
            out.append(f"### {seg.get('heading', f'Beat {seg.get('beat')}, turn {seg.get('turn')}')}")
            out.append(_fenced(seg.get("text", "").rstrip()))
            for wf in seg.get("wireframes") or []:
                out.append(_fenced(wf.rstrip()))

    unresolved = export.get("unresolved") or {}
    out.append("## Not Resolved Here")
    oq = unresolved.get("open_questions") or []
    parked = unresolved.get("parked") or []
    if oq:
        out.append("Open questions (verbatim from the session):")
        out.append(_fenced("\n".join(f"- {q}" for q in oq)))
    if parked:
        out.append("Parked decisions (never resolved — not ledger entries):")
        out.append(_fenced("\n".join(f"- D{p['number']:03d} {p['title']} ({p['disposition']})"
                                     for p in parked)))
    if not oq and not parked:
        out.append("- (session exported no unresolved items — verify against the source)")

    return "\n\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description="woz-session/v1 JSON → archwright discovery artifact")
    ap.add_argument("export_json")
    ap.add_argument("-o", "--design-dir", default="design")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing import (deliberate snapshot refresh)")
    args = ap.parse_args()

    try:
        export = json.loads(Path(args.export_json).read_text(encoding="utf-8"))
    except OSError as e:
        print(f"ERROR: cannot read {args.export_json}: {e}", file=sys.stderr)
        sys.exit(2)
    except json.JSONDecodeError as e:
        fail(f"not valid JSON: {e}")

    errors = validate(export)
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    content = render(export)
    m = re.search(r"^id: (\S+)$", content, re.MULTILINE)
    out_path = Path(args.design_dir) / "discovery" / "woz" / f"{m.group(1)}.md"
    if out_path.exists() and not args.force:
        print(f"ERROR: {out_path} exists — imports are deliberate snapshot refreshes; "
              f"re-run with --force to overwrite (grill Q1)", file=sys.stderr)
        sys.exit(2)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8", newline="\n")
    print(f"imported: {out_path}")


if __name__ == "__main__":
    main()
